### ISSUE TITLE
Describe occurrenceID stability and which changes will trigger GBIF to contact the publisher

### ISSUE THREAD

**Issue by CecSve** [gbif/tech-docs#106]
OccurrenceID stability information should be added to https://github.com/gbif/tech-docs/blob/main/en/data-publishing/modules/ROOT/pages/data-quality-recommendations.adoc

We could incorporate part of this [wiki](https://github.com/gbif/ingestion-management/wiki/Advice-for-publishers), but it should be less prose and more technical, with reference to thresholds and perhaps also triples. Anything the publisher would need to know can happen if ID stability is lost or compromised.

**Comment by CecSve** [comment]
should probably be referenced somewhere in data use so readers can learn more

**Comment by ManonGros** [comment]
maybe we could reuse what Kumiko wrote here: https://data-blog.gbif.org/post/improve-identifier-stability/?

**Comment by jhnwllr** [comment]
@CecSve I have update the section now to include a few paragraphs about id stability and our workflow around maintaining it. If you find it acceptable, feel free to close this issue.
