### ISSUE TITLE
documentation of occurrence predicates is broken and lacks info

### ISSUE THREAD

**Issue by MortenHofft** [gbif/tech-docs#112]
https://techdocs.gbif.org/en/openapi/v1/occurrence#/Searching%20occurrences/predicateSearchOccurrence

The example fails - and there is no real description of how to search with a predicate.

Perhaps just add an example body like in https://techdocs.gbif.org/en/openapi/v1/occurrence#/Occurrence%20downloads/requestDownload ?

**Comment by MattBlissett** [comment]
This is fixed for the new environment, so won't be visible until some time in January.
