### ISSUE TITLE
Add support for icons in the data quality requirements page

### ISSUE THREAD

**Issue by CecSve** [gbif/tech-docs#116]
I have tried to set up icons for the [data quality requirements page](https://github.com/gbif/tech-docs/blob/main/en/data-publishing/modules/ROOT/pages/data-quality-recommendations.adoc) but I must be missing something since [the icons do not render](https://techdocs.gbif-uat.org/en/data-publishing/data-quality-recommendations). Currently, I am testing two different ways of enabling the icon in the page text, which is why it looks a bit chaotic. 

I have added the images to the supplemental_ui under icons: https://github.com/gbif/tech-docs/tree/main/supplemental_ui/images/icons and made a CSS file: https://github.com/gbif/tech-docs/blob/main/supplemental_ui/css/icons.css, trying to replicate the setup for the [training docs](https://github.com/gbif/training).

I would like to display the icons like notes, similar to the training docs: https://training.gbif-uat.org/en/epn/engaging-stakeholders, but I would also like to include them in a smaller size in tables, similar to the tables in https://techdocs.gbif.org/en/data-use/download-formats#simple.

Could this be enabled, please?

**Comment by CecSve** [comment]
It might be enough to just enable the smaller icons and put them in the text description, similar to https://techdocs.gbif.org/en/data-use/download-formats#simple.

**Comment by MattBlissett** [comment]
The small icons in the download format table are just inline images:

```
image:ROOT::logo/gbif/symbol.svg[24,24] A specific interpretation issue
```

But to save repeating that, aliases `{gbif_source}` and `{dwc_source}` are defined in en/data-use/antora.yml.

I have fixed the admonition icon syntax (you were 95% there), but I'm not sure these will be clear if rendered at a small size in the table.

**Comment by CecSve** [comment]
Thank you! I have tried replicating what you did for the aliases, but it renders `24` whether I use aliases or write the full path. I thought it was due to the .png format, but it seems it is the same issue if I use .svg. Is it too big or complex perhaps?

**Comment by MattBlissett** [comment]
I've fixed it. The alternative text was missing, hence the 24 — the first argument is supposed to be the alt-text, not the width.

**Comment by CecSve** [comment]
Thanks - I tried that option too after reading the documentation and added 'taxon' as the alternative text, but then it was split into two lines ('tax' and 'on'). It looks good - thanks for keeping in all options. I can see one is poor resolution so will avoid using that.
