### ISSUE TITLE
Move rule based annotations API docs to UAT only view 

### ISSUE THREAD

**Issue by jhnwllr** [gbif/tech-docs#75]
@marcos-lg, I am not sure what is involved to move the rule based annotations API docs to the tech docs, but I think it should be moved.  

http://prodws-vh.gbif.org:8124/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

I found out it is possible to put this at the top of the page, so that it is only available on UAT. 

```asciidoc
= Rule Based Annotations
ifeval::["{env}" == "prod"]
:page-unpublish:
endif::[]

NOTE: This is an **experimental feature**, and the implementation may change throughout 2024.  The feature is currently available for preview on the GBIF test environment, https://www.gbif-uat.org/[GBIF-UAT.org].

```

I suppose it should go here: 

https://github.com/gbif/tech-docs/blob/main/en/openapi-v1/modules/ROOT/pages/registry.adoc

But I think we need some input from 
@MattBlissett

**Comment by MattBlissett** [comment]
Mostly done @marcos-lg, but still required is an additional `@Tag` in OccurrenceResource.java, then `@Tag` annotations in the occurrence-annotation controllers.

See https://github.com/gbif/metrics/blob/master/metrics-ws/src/main/java/org/gbif/metrics/ws/resources/OccurrenceCubeResource.java#L70 for how this works.

**Comment by marcos-lg** [comment]
Just added them: https://github.com/gbif/occurrence-annotation/commit/d6ea04260188fa4828a3ec33d6118167b226b435
