### ISSUE TITLE
MS & KY not listed in the Try it out system, even though they seem to be supported in the code

### ISSUE THREAD

**Issue by qgroom** [gbif/tech-docs#89]
The countriesOfCoverage and countriesOfResearcher in the Literature API seems to support Montserrat (MS) and the Cayman Island (KY). However, the [technical documents page](https://techdocs.gbif.org/en/openapi/v1/literature#/Literature/search) does not allow selection of these regions in the `Try it out`.

**Comment by MattBlissett** [comment]
Hi Quentin,

I see these entries in the list, although they are in alphabetical order of the English name, so KY is with most of the entries beginning with C.

**Comment by qgroom** [comment]
Ahhhh! That's a weird logic.
Not exactly the most serious of "features". I would not be offended if you closed it without a fix.
