### ISSUE TITLE
`HTTP/2` vs `HTTP/1.1`

### ISSUE THREAD

**Issue by damianooldoni** [gbif/tech-docs#96]
Feedback on [API SQL Downloads](https://techdocs.gbif.org/en/data-use/api-sql-downloads) ([Github source for this page](../blob/main/./en/data-use/modules/ROOT/pages/api-sql-downloads.adoc))

While running the example in documentation, I get `HTTP/1.1 201 Created` instead of `HTTP/2 201` as mentioned in doc:
> If the query is accepted the first line of output should be HTTP/2 201

If I provide wrong credentials, I get `HTTP/1.1 401 Unauthorized` insetad of `HTTP/2 401`:
> HTTP/2 401 means your username or password is incorrect

I wonder if the `HTTP/1.1` version I get is related to my machine or is it at GBIF side? if it is due to my machine, maybe it should be mentioned in documentation. If it is a GBIF side, maybe `HTTP/2` should be replaced by `HTTP/1.1`.

Thanks in advance!

**Comment by MattBlissett** [comment]
It is due to the version of Curl on your machine being a bit older than mine, I'll update it later.
